#!/usr/bin/env python3
import os
import sys
import json

# Setup paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.getenv("TASKS_REPO_ROOT", os.path.dirname(SCRIPT_DIR))
sys.path.append(REPO_ROOT)

from scripts.lib import io

TOOLS_JSON = os.path.join(REPO_ROOT, "docs", "interop", "tool_definitions.json")
TOOLS_MD = os.path.join(REPO_ROOT, "docs", "interop", "TOOLS.md")
TOOLS_SH = os.path.join(REPO_ROOT, "scripts", "tools.sh")

def generate_markdown(tools):
    lines = [
        "# Agent Tools Reference",
        "",
        "This file is auto-generated. Do not edit manually.",
        "",
        "| Tool | Risk | Description | Usage |",
        "| :--- | :--- | :--- | :--- |"
    ]
    
    for tool in tools:
        name = tool["name"]
        risk = tool.get("risk_level", "N/A")
        desc = tool["description"]
        
        # Simple usage example
        params = tool["parameters"].get("properties", {})
        args = ", ".join([f"{k}" for k in params.keys()])
        usage = f"`{name}({args})`"
        
        lines.append(f"| {name} | **{risk}** | {desc} | {usage} |")
    
    return "\n".join(lines) + "\n"

def generate_shell(tools):
    lines = [
        "#!/bin/bash",
        "# Auto-generated by scripts/generate_tools.py",
        "",
        "# Source this file to enable tool aliases in your shell",
        ""
    ]
    
    for tool in tools:
        name = tool["name"]
        impl = tool.get("implementation", "")
        if not impl:
            continue
            
        lines.append(f"function {name}() {{")
        lines.append(f"    # Risk Level: {tool.get('risk_level', 'L1')}")
        
        # Extract the base command
        # We want to remove any part of the string from the first '{' onwards,
        # AND if the word before '{' looks like a flag (starts with -- or -), remove that too.
        import re
        
        # 1. Split by space
        parts = impl.split(' ')
        base_parts = []
        for p in parts:
            if '{' in p:
                # Found a placeholder. If the previous part was a flag, remove it.
                if base_parts and base_parts[-1].startswith('-'):
                    base_parts.pop()
                break
            base_parts.append(p)
            
        base_cmd = ' '.join(base_parts).strip()
        
        lines.append(f"    {base_cmd} \"$@\"")
        lines.append(f"}}")
        lines.append("")
        
    return "\n".join(lines)

def main():
    if not os.path.exists(TOOLS_JSON):
        print(f"Error: {TOOLS_JSON} not found.")
        sys.exit(1)
        
    data = io.read_json(TOOLS_JSON)
    tools = data.get("tools", [])
    
    # Generate MD
    print(f"Generating {TOOLS_MD}...")
    md_content = generate_markdown(tools)
    io.write_atomic(TOOLS_MD, md_content)
    
    # Generate SH
    print(f"Generating {TOOLS_SH}...")
    sh_content = generate_shell(tools)
    io.write_atomic(TOOLS_SH, sh_content)
    
    print("Generation complete.")

if __name__ == "__main__":
    main()
