#!/bin/bash
# Auto-generated by scripts/generate_tools.py

# Source this file to enable tool aliases in your shell

function task_create() {
    # Risk Level: L1
    python3 scripts/tasks.py create "$@"
}

function task_list() {
    # Risk Level: L0
    python3 scripts/tasks.py list "$@"
}

function task_update() {
    # Risk Level: L1
    python3 scripts/tasks.py update "$@"
}

function task_show() {
    # Risk Level: L0
    python3 scripts/tasks.py show "$@"
}

function task_context() {
    # Risk Level: L0
    python3 scripts/tasks.py context "$@"
}

function task_archive() {
    # Risk Level: L1
    python3 scripts/tasks.py archive "$@"
}

function memory_create() {
    # Risk Level: L1
    python3 scripts/memory.py create "$@"
}

function memory_list() {
    # Risk Level: L0
    python3 scripts/memory.py list "$@"
}

function memory_read() {
    # Risk Level: L0
    python3 scripts/memory.py read "$@"
}

function index_impact() {
    # Risk Level: L0
    python3 scripts/index.py impact "$@"
}

function index_add() {
    # Risk Level: L2
    python3 scripts/index.py add "$@"
}

function index_check() {
    # Risk Level: L0
    python3 scripts/index.py check "$@"
}

function agent_send() {
    # Risk Level: L1
    python3 scripts/comm.py send "$@"
}

function agent_read() {
    # Risk Level: L1
    python3 scripts/comm.py read "$@"
}

function agent_list() {
    # Risk Level: L0
    python3 scripts/comm.py list "$@"
}

function code_index_init() {
    # Risk Level: L2
    python3 scripts/code_index.py init "$@"
}

function code_index_refresh() {
    # Risk Level: L1
    python3 scripts/code_index.py index "$@"
}

function code_index_list() {
    # Risk Level: L0
    python3 scripts/code_index.py list "$@"
}

function code_index_search() {
    # Risk Level: L0
    python3 scripts/code_index.py search "$@"
}

function code_index_lookup() {
    # Risk Level: L0
    python3 scripts/code_index.py lookup "$@"
}

function code_index_references() {
    # Risk Level: L0
    python3 scripts/code_index.py references "$@"
}
